### ISSUE TITLE
Sanity checks 

### ISSUE THREAD

**Issue by Thomas-Moore-Creative** [Thomas-Moore-Creative/Climatology-generator-demo#26]
@matt-csiro is reporting that the 288 GISready files here:

`/g/data/es60/users/thomas_moore/clim_demo_results/daily/bran2020_GISready_results`

have, again, the "neutral is the same as la Nina" bug #23 

To regain confidence let's have a hard look at where we are and how we got here.

**Comment by Thomas-Moore-Creative** [comment]
we are here: `/g/data/es60/users/thomas_moore/clim_demo_results/daily/bran2020_GISready_results`
```
(base) tm4888@gadi-login-09 /g/data/es60/users/thomas_moore/clim_demo_results/daily ls -ltrh
total 20K
drwxr-sr-x 2 tm4888 es60 4.0K Jun  8 06:03 bran2020_final_results
drwxr-sr-x 3 tm4888 es60  12K Jun 10 08:30 bran2020_intermediate_results
drwxr-sr-x 6 tm4888 xv83 4.0K Jun 10 10:21 bran2020_GISready_results
```

**Comment by Thomas-Moore-Creative** [comment]
- [x] the `neutral` files **are the same** as `la_nina` files in `bran2020_GISready_results`

**Comment by matt-csiro** [comment]
I'm finding these files are the same...
/g/data/es60/users/thomas_moore/clim_demo_results/daily/bran2020_GISready_results/la_nina/temp/BRAN2020_temp_mth_01.nc, and, 
/g/data/es60/users/thomas_moore/clim_demo_results/daily/bran2020_GISready_results/neutral/temp/BRAN2020_temp_mth_01.nc

**Comment by Thomas-Moore-Creative** [comment]
## salt

![CleanShot 2024-06-13 at 06 39 52@2x](https://github.com/Thomas-Moore-Creative/Climatology-generator-demo/assets/36463906/55d48a3a-454c-4fee-b072-4ad971468f41)

![CleanShot 2024-06-13 at 06 44 21@2x](https://github.com/Thomas-Moore-Creative/Climatology-generator-demo/assets/36463906/4742fa97-2e46-484c-83aa-712f122dbc14)

![CleanShot 2024-06-13 at 06 42 06@2x](https://github.com/Thomas-Moore-Creative/Climatology-generator-demo/assets/36463906/929e41d4-2028-4013-80ee-bdfa0d3ecaa5)

**Comment by Thomas-Moore-Creative** [comment]
![CleanShot 2024-06-13 at 06 42 06@2x](https://github.com/Thomas-Moore-Creative/Climatology-generator-demo/assets/36463906/929e41d4-2028-4013-80ee-bdfa0d3ecaa5)

**Comment by Thomas-Moore-Creative** [comment]
![CleanShot 2024-06-13 at 06 44 21@2x](https://github.com/Thomas-Moore-Creative/Climatology-generator-demo/assets/36463906/4742fa97-2e46-484c-83aa-712f122dbc14)

**Comment by Thomas-Moore-Creative** [comment]
## u
![CleanShot 2024-06-13 at 06 46 06@2x](https://github.com/Thomas-Moore-Creative/Climatology-generator-demo/assets/36463906/37d92d3f-919b-4733-9b10-72a6803d5029)

**Comment by Thomas-Moore-Creative** [comment]
## temp

![CleanShot 2024-06-13 at 06 50 04@2x](https://github.com/Thomas-Moore-Creative/Climatology-generator-demo/assets/36463906/29732718-a49a-484f-8cf3-d29f6d394b32)

![CleanShot 2024-06-13 at 07 30 13@2x](https://github.com/Thomas-Moore-Creative/Climatology-generator-demo/assets/36463906/cd6cfdd8-f1b3-4fb8-8fcf-ae4467c04743)

**Comment by Thomas-Moore-Creative** [comment]
# Is a lack of sync in the `xv83` results backup the cause!?!

because of both a flakey NCI `gdata6` and my lack of storage space on `es60` I made this change to the GISready script over the weekend.

```
# Store the value in the dictionary
        #results_path = '/g/data/es60/users/thomas_moore/clim_demo_results/daily/bran2020_intermediate_results/'
        results_path = '/g/data/xv83/users/tm4888/PROJECTS/BRAN2020/results_backup/'
```

but is `/g/data/es60/users/thomas_moore/clim_demo_results/daily/bran2020_intermediate_results/` actually the same as `/g/data/xv83/users/tm4888/PROJECTS/BRAN2020/results_backup/` or was that backup sync **before** I fixed the #23 bug?

**Comment by Thomas-Moore-Creative** [comment]
## the `xv83` backup retained the #23 bugged files

```
(base) tm4888@gadi-login-04 /g/data/es60/users/thomas_moore/clim_demo_results/daily/bran2020_intermediate_results ls -ltrh *neutral*
-rw-r--r-- 1 tm4888 es60 465M May 27 11:33 BRAN2020_base_stats_eta_t_neutral_2024.05.22.11.07.01.nc
-rw-r--r-- 1 tm4888 es60 464M May 27 11:33 BRAN2020_base_stats_mld_neutral_2024.05.22.09.55.36.nc
-rw-r--r-- 1 tm4888 es60  16G May 27 11:33 BRAN2020_base_stats_salt_neutral_2024.05.22.02.52.35.nc
-rw-r--r-- 1 tm4888 es60  19G May 27 11:34 BRAN2020_base_stats_temp_neutral_2024.05.22.06.24.27.nc
-rw-r--r-- 1 tm4888 es60  23G May 27 11:35 BRAN2020_base_stats_u_neutral_2024.05.21.22.21.38.nc
-rw-r--r-- 1 tm4888 es60  23G May 27 11:36 BRAN2020_base_stats_v_neutral_2024.05.22.11.17.59.nc
-rw-r--r-- 1 tm4888 es60 350M May 27 11:36 BRAN2020_quantile_stats_eta_t_neutral_2024.05.22.11.07.01.nc
-rw-r--r-- 1 tm4888 es60 361M May 27 11:36 BRAN2020_quantile_stats_mld_neutral_2024.05.22.09.55.36.nc
-rw-r--r-- 1 tm4888 es60  11G May 27 11:37 BRAN2020_quantile_stats_salt_neutral_2024.05.22.02.52.35.nc
-rw-r--r-- 1 tm4888 es60  12G May 27 11:37 BRAN2020_quantile_stats_temp_neutral_2024.05.22.06.24.27.nc
-rw-r--r-- 1 tm4888 es60  16G May 27 11:38 BRAN2020_quantile_stats_u_neutral_2024.05.21.22.21.38.nc
-rw-r--r-- 1 tm4888 es60  16G May 27 11:39 BRAN2020_quantile_stats_v_neutral_2024.05.22.11.17.59.nc
(base) tm4888@gadi-login-04 /g/data/es60/users/thomas_moore/clim_demo_results/daily/bran2020_intermediate_results
```

```
(base) tm4888@gadi-login-03 /g/data/xv83/users/tm4888/PROJECTS/BRAN2020/results_backup ls -ltrh *neutral*
-rw-r--r-- 1 tm4888 es60  19G May 18 23:03 BRAN2020_base_stats_temp_neutral_2024.05.18.18.54.38.nc
-rw-r--r-- 1 tm4888 es60  17G May 18 23:49 BRAN2020_base_stats_salt_neutral_2024.05.18.20.03.31.nc
-rw-r--r-- 1 tm4888 es60  12G May 19 02:52 BRAN2020_quantile_stats_temp_neutral_2024.05.18.18.54.38.nc
-rw-r--r-- 1 tm4888 es60  11G May 19 03:20 BRAN2020_quantile_stats_salt_neutral_2024.05.18.20.03.31.nc
-rw-r--r-- 1 tm4888 es60  23G May 20 00:29 BRAN2020_base_stats_u_neutral_2024.05.19.20.08.43.nc
-rw-r--r-- 1 tm4888 es60  16G May 20 01:11 BRAN2020_quantile_stats_u_neutral_2024.05.19.20.54.39.nc
-rw-r--r-- 1 tm4888 es60  23G May 20 11:38 BRAN2020_base_stats_v_neutral_2024.05.20.07.34.07.nc
-rw-r--r-- 1 tm4888 es60  16G May 20 12:11 BRAN2020_quantile_stats_v_neutral_2024.05.20.07.36.36.nc
-rw-r--r-- 1 tm4888 es60 471M May 20 14:30 BRAN2020_base_stats_mld_neutral_2024.05.20.14.15.51.nc
-rw-r--r-- 1 tm4888 es60 365M May 20 14:33 BRAN2020_quantile_stats_mld_neutral_2024.05.20.14.15.51.nc
-rw-r--r-- 1 tm4888 es60 468M May 20 14:45 BRAN2020_base_stats_eta_t_neutral_2024.05.20.14.30.28.nc
-rw-r--r-- 1 tm4888 es60 353M May 20 14:48 BRAN2020_quantile_stats_eta_t_neutral_2024.05.20.14.30.28.nc
(base) tm4888@gadi-login-03 /g/data/xv83/users/tm4888/PROJECTS/BRAN2020/results_backup
```

**Comment by Thomas-Moore-Creative** [comment]
### `la_nina` shouldn't be bugged but check they are the same to be sure

```
(base) tm4888@gadi-login-04 /g/data/es60/users/thomas_moore/clim_demo_results/daily/bran2020_intermediate_results ls -ltrh *la_nina*
-rw-r--r-- 1 tm4888 es60  19G May 19 06:54 BRAN2020_base_stats_temp_la_nina_2024.05.18.18.54.38.nc
-rw-r--r-- 1 tm4888 es60  17G May 19 07:08 BRAN2020_base_stats_salt_la_nina_2024.05.18.20.03.31.nc
-rw-r--r-- 1 tm4888 es60  11G May 19 10:41 BRAN2020_quantile_stats_salt_la_nina_2024.05.18.20.03.31.nc
-rw-r--r-- 1 tm4888 es60  12G May 19 16:45 BRAN2020_quantile_stats_temp_la_nina_2024.05.19.12.59.34.nc
-rw-r--r-- 1 tm4888 es60  16G May 20 00:53 BRAN2020_quantile_stats_u_la_nina_2024.05.19.21.11.12.nc
-rw-r--r-- 1 tm4888 es60  23G May 20 05:12 BRAN2020_base_stats_u_la_nina_2024.05.20.00.30.07.nc
-rw-r--r-- 1 tm4888 es60  23G May 20 07:11 BRAN2020_base_stats_v_la_nina_2024.05.20.03.08.03.nc
-rw-r--r-- 1 tm4888 es60  16G May 20 12:01 BRAN2020_quantile_stats_v_la_nina_2024.05.20.07.49.04.nc
-rw-r--r-- 1 tm4888 es60 471M May 20 14:40 BRAN2020_base_stats_mld_la_nina_2024.05.20.14.15.51.nc
-rw-r--r-- 1 tm4888 es60 365M May 20 14:43 BRAN2020_quantile_stats_mld_la_nina_2024.05.20.14.15.51.nc
-rw-r--r-- 1 tm4888 es60 468M May 20 14:55 BRAN2020_base_stats_eta_t_la_nina_2024.05.20.14.30.28.nc
-rw-r--r-- 1 tm4888 es60 353M May 20 14:58 BRAN2020_quantile_stats_eta_t_la_nina_2024.05.20.14.30.28.nc
(base) tm4888@gadi-login-04 /g/data/es60/users/thomas_moore/clim_demo_results/daily/bran2020_intermediate_results
```
```
(base) tm4888@gadi-login-03 /g/data/xv83/users/tm4888/PROJECTS/BRAN2020/results_backup ls -ltrh *la_nina*
-rw-r--r-- 1 tm4888 es60  19G May 19 06:54 BRAN2020_base_stats_temp_la_nina_2024.05.18.18.54.38.nc
-rw-r--r-- 1 tm4888 es60  17G May 19 07:08 BRAN2020_base_stats_salt_la_nina_2024.05.18.20.03.31.nc
-rw-r--r-- 1 tm4888 es60  11G May 19 10:41 BRAN2020_quantile_stats_salt_la_nina_2024.05.18.20.03.31.nc
-rw-r--r-- 1 tm4888 es60  12G May 19 16:45 BRAN2020_quantile_stats_temp_la_nina_2024.05.19.12.59.34.nc
-rw-r--r-- 1 tm4888 es60  16G May 20 00:53 BRAN2020_quantile_stats_u_la_nina_2024.05.19.21.11.12.nc
-rw-r--r-- 1 tm4888 es60  23G May 20 05:12 BRAN2020_base_stats_u_la_nina_2024.05.20.00.30.07.nc
-rw-r--r-- 1 tm4888 es60  23G May 20 07:11 BRAN2020_base_stats_v_la_nina_2024.05.20.03.08.03.nc
-rw-r--r-- 1 tm4888 es60  16G May 20 12:01 BRAN2020_quantile_stats_v_la_nina_2024.05.20.07.49.04.nc
-rw-r--r-- 1 tm4888 es60 471M May 20 14:40 BRAN2020_base_stats_mld_la_nina_2024.05.20.14.15.51.nc
-rw-r--r-- 1 tm4888 es60 365M May 20 14:43 BRAN2020_quantile_stats_mld_la_nina_2024.05.20.14.15.51.nc
-rw-r--r-- 1 tm4888 es60 468M May 20 14:55 BRAN2020_base_stats_eta_t_la_nina_2024.05.20.14.30.28.nc
-rw-r--r-- 1 tm4888 es60 353M May 20 14:58 BRAN2020_quantile_stats_eta_t_la_nina_2024.05.20.14.30.28.nc
(base) tm4888@gadi-login-03 /g/data/xv83/users/tm4888/PROJECTS/BRAN2020/results_backup
```

**Comment by Thomas-Moore-Creative** [comment]
# ToDo

- [x] rerun `neutral` GISready files from `/g/data/es60/users/thomas_moore/clim_demo_results/daily/bran2020_intermediate_results/`
- [x] remove the `xv83` backup

**Comment by Thomas-Moore-Creative** [comment]
```
next nc file time: 2024-06-13 11:08:20.988763
Searching for core variable: eta_t_
Searching for phase: neutral
writing: /g/data/es60/users/thomas_moore/clim_demo_results/daily/bran2020_GISready_results/neutral/eta_t/BRAN2020_eta_t_mth_01.nc
next nc file time: 2024-06-13 11:08:27.117811
writing: /g/data/es60/users/thomas_moore/clim_demo_results/daily/bran2020_GISready_results/neutral/eta_t/BRAN2020_eta_t_mth_02.nc
next nc file time: 2024-06-13 11:08:33.186271
writing: /g/data/es60/users/thomas_moore/clim_demo_results/daily/bran2020_GISready_results/neutral/eta_t/BRAN2020_eta_t_mth_03.nc
next nc file time: 2024-06-13 11:08:39.577865
writing: /g/data/es60/users/thomas_moore/clim_demo_results/daily/bran2020_GISready_results/neutral/eta_t/BRAN2020_eta_t_mth_04.nc
next nc file time: 2024-06-13 11:08:44.837404
writing: /g/data/es60/users/thomas_moore/clim_demo_results/daily/bran2020_GISready_results/neutral/eta_t/BRAN2020_eta_t_mth_05.nc
next nc file time: 2024-06-13 11:08:51.564630
writing: /g/data/es60/users/thomas_moore/clim_demo_results/daily/bran2020_GISready_results/neutral/eta_t/BRAN2020_eta_t_mth_06.nc
next nc file time: 2024-06-13 11:08:59.877194
writing: /g/data/es60/users/thomas_moore/clim_demo_results/daily/bran2020_GISready_results/neutral/eta_t/BRAN2020_eta_t_mth_07.nc
next nc file time: 2024-06-13 11:09:05.055109
writing: /g/data/es60/users/thomas_moore/clim_demo_results/daily/bran2020_GISready_results/neutral/eta_t/BRAN2020_eta_t_mth_08.nc
next nc file time: 2024-06-13 11:09:10.823118
writing: /g/data/es60/users/thomas_moore/clim_demo_results/daily/bran2020_GISready_results/neutral/eta_t/BRAN2020_eta_t_mth_09.nc
next nc file time: 2024-06-13 11:09:16.918351
writing: /g/data/es60/users/thomas_moore/clim_demo_results/daily/bran2020_GISready_results/neutral/eta_t/BRAN2020_eta_t_mth_10.nc
next nc file time: 2024-06-13 11:09:22.846078
writing: /g/data/es60/users/thomas_moore/clim_demo_results/daily/bran2020_GISready_results/neutral/eta_t/BRAN2020_eta_t_mth_11.nc
next nc file time: 2024-06-13 11:09:29.594871
writing: /g/data/es60/users/thomas_moore/clim_demo_results/daily/bran2020_GISready_results/neutral/eta_t/BRAN2020_eta_t_mth_12.nc
next nc file time: 2024-06-13 11:09:34.187804
>>> ALL DONE >>> end time: 2024-06-13 11:09:34.189164
```

**Comment by Thomas-Moore-Creative** [comment]
#  looks fixed

@matt-csiro  - could you repeat your same checks?

![CleanShot 2024-06-13 at 12 12 32@2x](https://github.com/Thomas-Moore-Creative/Climatology-generator-demo/assets/36463906/3c22ad68-adfb-4f4d-9283-218729f00b53)

**Comment by Thomas-Moore-Creative** [comment]
![CleanShot 2024-06-13 at 14 12 13@2x](https://github.com/Thomas-Moore-Creative/Climatology-generator-demo/assets/36463906/9fd6d43c-e38c-4dd1-beb1-14239980a9c4)
